name: CI

on: ["pull_request", "push"]

env:
  PORT: 3000

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with: { node-version: 24 }
      - run: corepack enable && yarn install --immutable
      - run: yarn lint:biome
      - run: yarn lint:eslint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with: { node-version: 24 }
      - run: corepack enable && yarn install --immutable
      - run: yarn generate:internal-api-schemas
      - run: yarn typecheck

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with: { node-version: 24 }
      - run: corepack enable && yarn install --immutable
      - run: yarn install-playwright-browser
      - run: yarn generate:internal-api-schemas
      - run: yarn test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with: { node-version: 24 }
      - run: corepack enable && yarn install --immutable
      - run: yarn playwright install chromium --with-deps
      - run: yarn generate:internal-api-schemas
      - run: yarn build:web-static
      - run: yarn e2e
